
# Exercise 1 Imputer 1

The goal of this exercise is to learn how to use an Imputer to fill missing values on basic example.

```python
train_data = [[7, 6, 5], 
              [4, np.nan, 5], 
              [1, 20, 8]]
```

1. Fit the `SimpleImputer` on the data. Print the `statistics_`. Check that the statistics match `np.nanmean(train_data, axis=0)`.

2. Fill the missing values in `train_data` using the fitted imputer and `transform`.

3. Fill the missing values in `test_data` using the fitted imputer and `transform`.

```python
test_data = [[np.nan, 1, 2], 
             [7, np.nan, 9], 
             [np.nan, 2, 4]]
```


In [19]:
import numpy as np
from sklearn.impute import SimpleImputer

train_data = [[7, 6, 5], 
              [4, np.nan, 5], 
              [1, 20, 8]]

# 1.
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit(train_data)
print(imp_mean.statistics_)

# testing
print(np.nanmean(train_data, axis=0))
print('---------')

# 2.
print(imp_mean.transform(train_data))
print('---------')

# 3.
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]

imp_mean1 = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean1.fit(test_data)
print(imp_mean.transform(test_data))


[ 4. 13.  6.]
[ 4. 13.  6.]
---------
[[ 7.  6.  5.]
 [ 4. 13.  5.]
 [ 1. 20.  8.]]
---------
[[ 4.  1.  2.]
 [ 7. 13.  9.]
 [ 4.  2.  4.]]
