
# Exercise 4 Optimize

The goal of this exercise is to learn to train the neural network. Once the architecture of the neural network is set there are two steps to train the neural network:

- `compile`:  The compilation step aims to set the loss function, to choose the algoithm to minimize the chosen loss function and to choose the metric the model outputs.

- The **optimizer**. We’ll stick with a pretty good default: the Adam gradient-based optimizer. Keras has many other optimizers you can look into as well.

- The **loss function**. Depending on the problem to solve: classification or regression Keras proposes different loss functions. In classification Keras distinguishes between `binary_crossentropy` (2 classes) and `categorical_crossentropy` (>2 classes), so we’ll use the latter.

- The **metric(s)**. A list of metrics. Depending on the problem to solve: classification or regression Keras proposes different loss functions. For example for classification the metric can be the accuracy.

- `fit`: Training a model in Keras literally consists only of calling fit() and specifying some parameters. There are a lot of possible parameters, but we’ll only manually supply a few:

  - The **training data**, commonly known as X and Y, respectively.
  - The **number of epochs** (iterations over the entire dataset) to train for.
  - The **batch size** (number of samples per gradient update) to use when training.

This article gives more details about **epoch** and **batch size**:

- https://machinelearningmastery.com/difference-between-a-batch-and-an-epoch/

1. Create the following neural network (classification):

- Set the right number of inputs variables
- hidden layer 1: 10 neurons and sigmoid as activation function.
- hidden layer 2: 5 neurons and sigmoid as activation function.
- output layer: 1 neuron and sigmoid as activation function.
- Choose the accuracy metric, the adam optimizer, the adapted loss and epoch smaller than 50.

Import the breast cancer data set from `sklearn.datasets` using `load_breast_cancer` and train the neural network on the data set.  

2. Scale the data using `StandardScaler` from `sklearn.preprocessing`. Train the neural network again.


In [12]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1.
# get the data_set
data = load_breast_cancer()

# load the target and the data
y, X = data.target, data.data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=43)

model = Sequential()

# set neurons, all layers (hidden and output)
model.add(Dense(10, input_dim=30, activation='sigmoid'))
model.add(Dense(5, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

# compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

'''
fit the data in the model, trining the model in Keras literally consists only
of calling fit() and specifuing some parameters

- The **training data**, commonly known as X and Y, respectively.
- The **number of epochs** (iterations over the entire dataset) to train for.
- The **batch size** (number of samples per gradient update) to use when training.
'''
model.fit(X_train, y_train, epochs=50, batch_size=300)

# testing
print(model.get_config()['layers'])

Epoch 1/50
2/2 [==============================] - 0s 2ms/step - loss: 0.7119 - accuracy: 0.3283
Epoch 2/50
2/2 [==============================] - 0s 2ms/step - loss: 0.7062 - accuracy: 0.3556
Epoch 3/50
2/2 [==============================] - 0s 1ms/step - loss: 0.7024 - accuracy: 0.3618
Epoch 4/50
2/2 [==============================] - 0s 2ms/step - loss: 0.6993 - accuracy: 0.3712
Epoch 5/50
2/2 [==============================] - 0s 3ms/step - loss: 0.6971 - accuracy: 0.3780
Epoch 6/50
2/2 [==============================] - 0s 2ms/step - loss: 0.6949 - accuracy: 0.5162
Epoch 7/50
2/2 [==============================] - 0s 4ms/step - loss: 0.6932 - accuracy: 0.5440
Epoch 8/50
2/2 [==============================] - 0s 2ms/step - loss: 0.6915 - accuracy: 0.5719
Epoch 9/50
2/2 [==============================] - 0s 2ms/step - loss: 0.6901 - accuracy: 0.5831
Epoch 10/50
2/2 [==============================] - 0s 3ms/step - loss: 0.6888 - accuracy: 0.6009
Epoch 11/50
2/2 [======================

In [13]:
scaler = StandardScaler()
scaler.fit(X_train, y_train)
print(X_train)
X_train_transformed = scaler.transform(X_train)
print(X_train_transformed)

model.fit(X_train_transformed, y_train, epochs=50, batch_size=300)

[[9.405e+00 2.170e+01 5.960e+01 ... 3.770e-02 2.872e-01 8.304e-02]
 [1.132e+01 2.708e+01 7.176e+01 ... 2.083e-02 2.849e-01 7.087e-02]
 [1.369e+01 1.607e+01 8.784e+01 ... 6.987e-02 3.323e-01 7.701e-02]
 ...
 [1.881e+01 1.998e+01 1.209e+02 ... 1.294e-01 2.567e-01 5.737e-02]
 [1.396e+01 1.705e+01 9.143e+01 ... 1.374e-01 3.068e-01 7.957e-02]
 [1.025e+01 1.618e+01 6.652e+01 ... 9.744e-02 2.608e-01 9.702e-02]]
[[-1.32109803  0.55900829 -1.31064248 ... -1.16561925 -0.0635106
  -0.07183175]
 [-0.78952224  1.7885245  -0.82230376 ... -1.4144706  -0.10101389
  -0.7457593 ]
 [-0.13164516 -0.72764157 -0.17654006 ... -0.69107582  0.67188003
  -0.40574984]
 ...
 [ 1.2895914   0.16592876  1.15113082 ...  0.18705817 -0.56083686
  -1.49333712]
 [-0.05669714 -0.50367765 -0.0323677  ...  0.30506711  0.25608267
  -0.26398694]
 [-1.08653848 -0.70250276 -1.03273919 ... -0.28438753 -0.49398316
   0.70232661]]
Epoch 1/50
2/2 [==============================] - 0s 2ms/step - loss: 0.6713 - accuracy: 0.6106
Epoch