
# Exercise 1: K-Fold

The goal of this exercise is to learn to use `KFold` to split the data set in a k-fold cross validation. Most of the time you won't use this function to split your data because this function is used by others as `cross_val_score` or `cross_validate` or `GridSearchCV` ... . But, this allows to understand the splitting and to create a custom one if needed.  

```python
X = np.array(np.arange(1,21).reshape(10,-1))
y = np.array(np.arange(1,11))
```

1. Using `KFold`, perform a 5-fold cross validation. For each fold, print the train index and test index. The expected output is:

    ```console
    Fold:  1
    TRAIN: [2 3 4 5 6 7 8 9] TEST: [0 1]

    Fold:  2
    TRAIN: [0 1 4 5 6 7 8 9] TEST: [2 3]

    Fold:  3
    TRAIN: [0 1 2 3 6 7 8 9] TEST: [4 5]

    Fold:  4
    TRAIN: [0 1 2 3 4 5 8 9] TEST: [6 7]

    Fold:  5
    TRAIN: [0 1 2 3 4 5 6 7] TEST: [8 9]
    ```


In [8]:
import numpy as np
from sklearn.model_selection import KFold

X = np.array(np.arange(1,21).reshape(10,-1))
y = np.array(np.arange(1,11))

kf = KFold(n_splits=5)
kf.get_n_splits(X)

print(X)

for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    # train_index as the name says its the index of the train
    # same gost to the test_index
    # then we can do this:
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
TRAIN: [2 3 4 5 6 7 8 9] TEST: [0 1]
[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]] [[1 2]
 [3 4]]
TRAIN: [0 1 4 5 6 7 8 9] TEST: [2 3]
[[ 1  2]
 [ 3  4]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]] [[5 6]
 [7 8]]
TRAIN: [0 1 2 3 6 7 8 9] TEST: [4 5]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [13 14]
 [15 16]
 [17 18]
 [19 20]] [[ 9 10]
 [11 12]]
TRAIN: [0 1 2 3 4 5 8 9] TEST: [6 7]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [17 18]
 [19 20]] [[13 14]
 [15 16]]
TRAIN: [0 1 2 3 4 5 6 7] TEST: [8 9]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]] [[17 18]
 [19 20]]
