06 exercice from day 01

**The sbuject**:

The goal of this exercise is to learn to access values of n-dimensional arrays efficiently.

1. Create an 2-dimensional array size 9,9 of 1s. Each value has to be an `int8`.
2. Using **slicing**, output this array:

    ```python
    array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 1, 1, 1, 1, 1, 0, 1],
        [1, 0, 1, 0, 0, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 0, 0, 1, 0, 1],
        [1, 0, 1, 1, 1, 1, 1, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)
    ```


https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html


In [32]:
import numpy as np

# what i thought it was supose to be done 
# a = np.random.randint(0, 2, size= (9, 9))

a = np.ones((9,9), dtype=np.int8)
a[1,1:8] = 0
a[7,1:8] = 0
a[3,3:6] = 0
a[5,3:6] = 0
a[1:8, 1] = 0
a[1:8, 7] = 0
a[3:6, 3] = 0
a[3:6, 5] = 0

# print(a)

# light solution

# a[1:8,1:8] = 0 
# a[2:7,2:7] = 1 
# a[3:6,3:6] = 0 
# a[4,4] = 1 


[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]
